name = "cp_lean"
version = "0.1.0"
defaultTargets = ["main"]

[[lean_lib]]
name = "Src"

[[lean_exe]]
name = "main"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"
